export type Lang = "en" | "ru";
export type Page = "home" | "expo" | "events" | "portfolio";

export const C = {
  en: {
    nav: {
      home: "Home",
      booths: "Expo Design & Construction",
      events: "Event Design & Production",
      portfolio: "Portfolio",
      contacts: "Contacts",
      cta: "Request a Proposal",
    },
    hero: {
      eyebrow: "Full-Service Exhibition & Event Partner · China",
      headline: "We Build Your\nVision in China",
      sub: "From concept to completion — exhibition booth design, construction, and corporate event production across China's major venues.",
      cta: "Request a Proposal",
      scroll: "Scroll",
    },
    about: {
      num: "01",
      label: "About Us",
      headline: "Your Trusted\nExhibition & Event\nPartner in China",
      body1: "We are a full-service exhibition and event company based in China, specializing in concept development, design, engineering, production and on-site execution. We partner with international brands to deliver world-class results across China's major exhibition centers — Shanghai, Beijing, Guangzhou, Shenzhen and beyond.",
      body2: "Our experienced team manages every project detail from initial briefing through to final dismantling, ensuring seamless communication and transparent delivery at every step of the process.",
      body3: "Beyond exhibitions, we deliver world-class event production — from intimate executive dinners and product launches to large-scale corporate conferences and brand activations. Every event is crafted with the same precision, creativity and on-the-ground expertise that defines our exhibition work.",
      cta: "Start a Project",
    },
    services: {
      num: "02",
      label: "Our Main Directions",
      headline: "What We Do",
      items: [
        {
          page: "expo" as Page,
          eyebrow: "01 / Exhibition",
          title: "Expo Design\n& Construction",
          body: "Custom booth concepts tailored to your brand identity. We handle everything: concept development, engineering, material sourcing, production, installation and dismantling — end to end.",
          cta: "Explore Service",
        },
        {
          page: "events" as Page,
          eyebrow: "02 / Events",
          title: "Event Design\n& Production",
          body: "Corporate conferences, product launches, gala dinners and brand activations. We create immersive experiences across China's premier venues that leave lasting impressions on your audience.",
          cta: "Explore Service",
        },
      ],
    },
    advantages: {
      num: "03",
      label: "Our Advantages",
      headline: "Why Choose Stagency",
      items: [
        {
          num: "01",
          title: "We Speak Your Language",
          body: "Our team communicates fluently in English, Russian, Italian and Chinese. No intermediaries, no misunderstandings — just clear, direct communication that keeps your project on track.",
        },
        {
          num: "02",
          title: "Your Trusted Partner in China",
          body: "We are your reliable eyes and hands on the ground. Full local presence, transparent reporting and complete accountability — from first brief to final handover.",
        },
        {
          num: "03",
          title: "Direct Vendor & Supplier Access",
          body: "Established relationships with China's best local manufacturers and suppliers give you competitive pricing, quality materials and faster production timelines than any overseas coordinator can offer.",
        },
        {
          num: "04",
          title: "Outstanding Design Capacity",
          body: "Our creative studio delivers remarkable, award-worthy designs for pavilions and events. We combine international aesthetics with deep knowledge of Chinese production capabilities.",
        },
      ],
    },
    portfolio: {
      num: "04",
      label: "Portfolio",
      headline: "Selected Works",
      cta: "View All Projects",
      items: [
        { id: "tech-pavilion", title: "Medical AI Company Pavilion", sub: "Shanghai · 260 sqm · 2024", tag: "Booth" },
        { id: "tech-lounge", title: "Tech Company Lounge", sub: "Beijing · 80 sqm · 2025", tag: "Booth" },
        { id: "beauty-pavilion", title: "Beauty Brand Pavilion", sub: "Saint Petersburg · 30 sqm · 2023", tag: "Booth" },
        { id: "executive-forum", title: "Executive Forum", sub: "Guangzhou · 2023", tag: "Event" },
        { id: "luxury-retail", title: "Luxury Retail Installation", sub: "Shanghai · 2023", tag: "Booth" },
        { id: "industry-summit", title: "Industry Summit", sub: "Chengdu · 2023", tag: "Event" },
      ],
    },
    contact: {
      num: "05",
      label: "Contact",
      headline: "Start Your\nProject with Us",
      sub: "Tell us about your upcoming exhibition or event. We respond within 24 hours.",
      form: {
        name: "Your Name",
        company: "Company",
        email: "Email Address",
        phone: "Phone / WhatsApp",
        message: "Project Details",
        submit: "Contact Us",
        sent: "Thank you — we will be in touch shortly.",
      },
      info: [
        { label: "Location", value: "Shanghai, China" },
        { label: "Email", value: "info@stagencychina.com" },
        { label: "Phone", value: "+86 21 0000 0000" },
        { label: "WhatsApp (RU)", value: "+7 000 000 00 00" },
      ],
    },
    footer: {
      tagline: "Exhibition & Event Partner in China",
      legal: "© 2026 Stagency by New Imagination DMC China. All rights reserved.",
      links: ["Expo Design & Construction", "Event Design & Production", "Portfolio", "Contacts"],
    },
    expoPage: {
      back: "Back to Home",
      breadcrumb: "Expo Design & Construction",
      headline: "Expo Design\n& Construction",
      sub: "From bespoke concept and engineering through to turnkey production and installation — we handle every aspect of your exhibition presence in China.",
      servicesLabel: "Our Services",
      services: [
        { num: "01", title: "Custom Stand Concept & Design", body: "Tailored design from initial brief to final 3D renders and walkthroughs. We ensure your booth reflects your brand identity perfectly while meeting venue regulations and audience expectations." },
        { num: "02", title: "Engineering & Technical Documentation", body: "Full structural engineering, material specifications and technical drawings compliant with Chinese exhibition venue requirements. Approved and ready for production." },
        { num: "03", title: "Turnkey Production & Manufacturing", body: "In-house and partner manufacturing across China. We oversee quality control at every production stage, ensuring your stand is delivered on time and to specification." },
        { num: "04", title: "Graphics, Branding & AV Integration", body: "Large-format printing, digital displays, LED walls and AV systems integrated seamlessly into your stand design. Consistent branding at every touchpoint." },
        { num: "05", title: "Installation & Dismantling", body: "Professional installation crews across all major Chinese venues — Shanghai NECC, Beijing CNCC, Guangzhou CIEC and more. We handle permits, logistics and full on-site coordination." },
        { num: "06", title: "Furniture, Lighting & Accessories", body: "Curated furniture packages, custom lighting design and branded accessories that elevate the overall experience and deliver a complete, polished result." },
      ],
      portfolioHeadline: "Expo Projects",
      contactHeadline: "Ready to Build\nYour Next Stand?",
    },
    eventsPage: {
      back: "Back to Home",
      breadcrumb: "Event Design & Production",
      headline: "Event Design\n& Production",
      sub: "We create immersive corporate events, product launches and brand experiences that leave lasting impressions — from concept through to on-site execution across China.",
      servicesLabel: "Our Services",
      services: [
        { num: "01", title: "Corporate Conferences & Summits", body: "End-to-end conference management for 50 to 5,000 delegates. Venue sourcing, stage design, AV production, simultaneous interpretation, delegate management and full logistics." },
        { num: "02", title: "Product Launches & Presentations", body: "Memorable launch events that generate media coverage and audience engagement. From intimate press showrooms to large-scale theatrical reveals at China's premier venues." },
        { num: "03", title: "Gala Dinners & Award Ceremonies", body: "Elegant atmospheric dinners and award ceremonies with full décor design, entertainment programming, catering coordination and end-to-end event production." },
        { num: "04", title: "Brand Activations & Pop-Ups", body: "Immersive brand experiences that connect your audience with your product in unexpected, memorable ways. We design, build and operate activations that drive engagement." },
        { num: "05", title: "Stage Design & AV Production", body: "Custom stage concepts, architectural lighting design, LED walls and video mapping, professional sound engineering and live streaming solutions for any scale of event." },
        { num: "06", title: "On-Site Management & Logistics", body: "Dedicated project managers and experienced on-site teams who ensure flawless execution from venue setup through post-event breakdown. Your single point of contact throughout." },
      ],
      portfolioHeadline: "Event Projects",
      contactHeadline: "Ready to Create\nYour Next Event?",
    },
    portfolioPage: {
      headline: "All Projects",
      sub: "Exhibition booths, corporate events and brand experiences delivered across China.",
      filters: { all: "All Projects", booth: "Booths", event: "Events" },
      cta: "Start Your Project",
    },
  },
  ru: {
    nav: {
      home: "Главная",
      booths: "Стенды и застройка",
      events: "Мероприятия и продакшн",
      portfolio: "Портфолио",
      contacts: "Контакты",
      cta: "Запросить предложение",
    },
    hero: {
      eyebrow: "Полный цикл услуг по выставкам и мероприятиям · Китай",
      headline: "Воплощаем ваше\nвидение в Китае",
      sub: "От концепции до реализации — проектирование и строительство стендов, организация корпоративных мероприятий по всему Китаю.",
      cta: "Запросить предложение",
      scroll: "Листать",
    },
    about: {
      num: "01",
      label: "О компании",
      headline: "Ваш надёжный партнёр\nпо выставкам и мероприятиям\nв Китае",
      body1: "Мы — полноцикловый партнёр в сфере выставок и мероприятий, базирующийся в Китае. Специализируемся на разработке концепций, дизайне, инжиниринге, производстве и реализации «под ключ». Мы работаем с международными брендами и обеспечиваем результат мирового уровня на крупнейших выставочных площадках Китая — Шанхай, Пекин, Гуанчжоу, Шэньчжэнь и другие города.",
      body2: "Наша опытная команда управляет каждой деталью проекта — от первого брифа до финального демонтажа, обеспечивая прозрачную коммуникацию и контролируемую реализацию на каждом этапе.",
      body3: "Помимо выставок, мы организуем мероприятия мирового уровня — от камерных деловых ужинов и запусков продуктов до масштабных корпоративных конференций и брендовых активаций. Каждое мероприятие создаётся с той же точностью, креативностью и экспертизой, что определяют нашу выставочную работу.",
      cta: "Начать проект",
    },
    services: {
      num: "02",
      label: "Наши направления",
      headline: "Что мы делаем",
      items: [
        {
          page: "expo" as Page,
          eyebrow: "01 / Стенды",
          title: "Стенды и\nзастройка",
          body: "Индивидуальные концепции, адаптированные к вашему бренду. Дизайн, инжиниринг, закупка материалов, производство, монтаж и демонтаж — всё под ключ.",
          cta: "Подробнее",
        },
        {
          page: "events" as Page,
          eyebrow: "02 / Мероприятия",
          title: "Мероприятия\nи продакшн",
          body: "Конференции, запуски продуктов, гала-ужины и брендовые активации. Создаём иммерсивные пространства на лучших площадках Китая, которые запоминаются надолго.",
          cta: "Подробнее",
        },
      ],
    },
    advantages: {
      num: "03",
      label: "Наши преимущества",
      headline: "Почему Stagency",
      items: [
        {
          num: "01",
          title: "Мы говорим на вашем языке",
          body: "Наша команда свободно общается на английском, русском, итальянском и китайском языках. Никаких посредников и недопонимания — только чёткая и прямая коммуникация, которая держит ваш проект под контролем.",
        },
        {
          num: "02",
          title: "Ваш надёжный партнёр в Китае",
          body: "Мы — ваши глаза и руки на месте. Полное локальное присутствие, прозрачная отчётность и полная ответственность — от первого брифа до финальной сдачи.",
        },
        {
          num: "03",
          title: "Прямой доступ к поставщикам и производителям",
          body: "Налаженные связи с лучшими китайскими производителями и поставщиками обеспечивают конкурентные цены, качественные материалы и более короткие сроки производства, чем может предложить любой зарубежный координатор.",
        },
        {
          num: "04",
          title: "Выдающийся дизайн-потенциал",
          body: "Наша творческая студия создаёт яркие, достойные наград проекты для павильонов и мероприятий, сочетая международную эстетику с глубоким знанием возможностей китайского производства.",
        },
      ],
    },
    portfolio: {
      num: "04",
      label: "Портфолио",
      headline: "Избранные проекты",
      cta: "Все проекты",
      items: [
        { id: "tech-pavilion", title: "Павильон медицинской AI компании", sub: "Шанхай · 260 м² · 2024", tag: "Стенд" },
        { id: "tech-lounge", title: "Лаундж технологической компании", sub: "Пекин · 80 м² · 2025", tag: "Стенд" },
        { id: "beauty-pavilion", title: "Павильон бьюти-бренда", sub: "Санкт-Петербург · 30 м² · 2023", tag: "Стенд" },
        { id: "executive-forum", title: "Корпоративный форум", sub: "Гуанчжоу · 2023", tag: "Мероприятие" },
        { id: "luxury-retail", title: "Люксовая инсталляция", sub: "Шанхай · 2023", tag: "Стенд" },
        { id: "industry-summit", title: "Отраслевой саммит", sub: "Чэнду · 2023", tag: "Мероприятие" },
      ],
    },
    contact: {
      num: "05",
      label: "Контакты",
      headline: "Начните ваш\nпроект с нами",
      sub: "Расскажите о вашем проекте. Мы отвечаем в течение 24 часов.",
      form: {
        name: "Ваше имя",
        company: "Компания",
        email: "Электронная почта",
        phone: "Телефон / WhatsApp",
        message: "Детали проекта",
        submit: "Связаться с нами",
        sent: "Спасибо — мы свяжемся с вами в ближайшее время.",
      },
      info: [
        { label: "Адрес", value: "Шанхай, Китай" },
        { label: "Email", value: "info@stagencychina.com" },
        { label: "Телефон", value: "+86 21 0000 0000" },
        { label: "WhatsApp", value: "+7 000 000 00 00" },
      ],
    },
    footer: {
      tagline: "Партнёр по выставкам и мероприятиям в Китае",
      legal: "© 2026 Stagency by New Imagination DMC China. Все права защищены.",
      links: ["Стенды и застройка", "Мероприятия и продакшн", "Портфолио", "Контакты"],
    },
    expoPage: {
      back: "На главную",
      breadcrumb: "Стенды и застройка",
      headline: "Стенды и\nзастройка",
      sub: "От авторской концепции и инжиниринга до производства и монтажа под ключ — мы берём на себя все аспекты вашего выставочного присутствия в Китае.",
      servicesLabel: "Наши услуги",
      services: [
        { num: "01", title: "Концепция и дизайн стенда", body: "Авторский дизайн от брифа до финального 3D-рендера и виртуального тура. Ваш стенд безупречно отражает идентичность бренда и соответствует требованиям площадки." },
        { num: "02", title: "Инжиниринг и техническая документация", body: "Полный комплект конструкторской документации, соответствующий требованиям китайских выставочных площадок. Согласованный и готовый к производству." },
        { num: "03", title: "Производство и изготовление", body: "Собственное и партнёрское производство по всему Китаю с контролем качества на каждом этапе. Сдача в срок и в соответствии со спецификацией." },
        { num: "04", title: "Графика, брендинг и AV-интеграция", body: "Широкоформатная печать, цифровые дисплеи, LED-экраны и AV-системы, органично интегрированные в дизайн стенда. Единый фирменный стиль во всех точках контакта." },
        { num: "05", title: "Монтаж и демонтаж", body: "Профессиональные монтажные бригады на всех крупных площадках Китая — NECC Шанхай, CNCC Пекин, CIEC Гуанчжоу. Разрешения, логистика и координация на площадке." },
        { num: "06", title: "Мебель, освещение и аксессуары", body: "Мебельные пакеты, дизайн освещения и фирменные аксессуары, которые создают целостный, профессиональный образ вашего стенда." },
      ],
      portfolioHeadline: "Проекты стендов",
      contactHeadline: "Готовы построить\nваш следующий стенд?",
    },
    eventsPage: {
      back: "На главную",
      breadcrumb: "Мероприятия и продакшн",
      headline: "Мероприятия\nи продакшн",
      sub: "Создаём иммерсивные корпоративные мероприятия, запуски продуктов и брендовые активации — от концепции до реализации на площадке по всему Китаю.",
      servicesLabel: "Наши услуги",
      services: [
        { num: "01", title: "Конференции и корпоративные саммиты", body: "Управление конференциями от 50 до 5000 участников. Подбор площадки, дизайн сцены, AV-продакшн, синхронный перевод, управление участниками и полная логистика." },
        { num: "02", title: "Запуски продуктов и презентации", body: "Запоминающиеся события для освещения в СМИ и вовлечения аудитории. От камерных пресс-румов до масштабных театральных презентаций на лучших площадках Китая." },
        { num: "03", title: "Гала-ужины и церемонии награждения", body: "Элегантные атмосферные ужины и церемонии награждения — полное оформление, развлекательная программа, координация кейтеринга и продакшн мероприятия под ключ." },
        { num: "04", title: "Брендовые активации и поп-апы", body: "Иммерсивный брендовый опыт, который связывает вашу аудиторию с продуктом неожиданными и запоминающимися способами. Проектируем, строим и управляем." },
        { num: "05", title: "Дизайн сцены и AV-продакшн", body: "Авторские концепции сцен, архитектурный световой дизайн, LED-экраны и видеомэппинг, профессиональное звуковое оформление и решения для прямых трансляций." },
        { num: "06", title: "Управление мероприятием и логистика", body: "Выделенные менеджеры проекта и опытные команды на площадке, обеспечивающие безупречную реализацию от подготовки площадки до финального демонтажа." },
      ],
      portfolioHeadline: "Проекты мероприятий",
      contactHeadline: "Готовы создать\nваше следующее мероприятие?",
    },
    portfolioPage: {
      headline: "Все проекты",
      sub: "Выставочные стенды, корпоративные мероприятия и брендовые активации по всему Китаю.",
      filters: { all: "Все проекты", booth: "Стенды", event: "Мероприятия" },
      cta: "Начать проект",
    },
  },
};

export type ContentType = typeof C.en;
